title: Research Group
description: The homepage of Research Group

# disabled because we are using a custom domain
#baseurl: /business-frontpage 

color-scheme: "#2D9596" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages
  - .htaccess

exclude:
  - .sass-cache
